# Salila Text2SQL 评估配置 - 真实Sakila数据集
evaluation:
  name: "Sakila Text2SQL 真实数据评估"
  description: "使用真实Sakila数据库进行Text2SQL系统评估"
  
# 数据集配置
dataset:
  # 使用转换后的Sakila数据集
  test_file: "../data/sakila_real.json"
  
  # 数据库知识库文件
  ddl_file: "../data/ddl_statements.yaml"
  db_description_file: "../data/db_description.yaml"

# 数据库连接配置（用于执行准确率测试）
database:
  enabled: true  # 启用真实数据库连接
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "sakila"
  
  # 数据库隔离设置
  isolation:
    enabled: true
    test_database: "sakila_test"  # 测试专用数据库
    backup_before_test: true
    restore_after_test: true

# Text2SQL系统配置
text2sql_system:
  type: "rag"  # 使用RAG系统
  
  # OpenAI配置
  openai:
    api_key: "{{APIKEY}}"
    api_base: "https://api.gptsapi.net"
    model: "gpt-4o-mini-2024-07-18"
    embedding_model: "text-embedding-3-small"
    temperature: 0.1
    max_tokens: 1000
  
  # RAG检索配置
  retrieval:
    top_k: 5
    similarity_threshold: 0.7
    use_vector_db: false  # 使用简化版本，不需要Milvus

# 评估指标配置
metrics:
  # 执行准确率（启用）
  execution_accuracy:
    enabled: true
    weight: 0.4
    timeout: 30  # SQL执行超时时间（秒）
  
  # 语法正确率
  syntax_accuracy:
    enabled: true
    weight: 0.2
  
  # 语义相似度
  semantic_similarity:
    enabled: true
    weight: 0.2
    embedding_weight: 0.7  # 嵌入相似度权重
    structural_weight: 0.3  # 结构相似度权重
  
  # 检索召回率
  retrieval_recall:
    enabled: true
    weight: 0.2
    table_weight: 0.4
    column_weight: 0.4
    key_column_weight: 0.2

# 报告配置
reporting:
  # 输出目录
  output_dir: "../results"
  
  # 报告格式
  formats:
    - "json"
    - "html"
  
  # 详细程度
  detail_level: "full"  # full, summary, minimal
  
  # 是否保存中间结果
  save_intermediate: true
  
  # HTML报告样式
  html_style: "modern"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "../logs/evaluation.log" 